name: Deploy eSIM Provisioning System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest backend/tests/ -v
    
    - name: Lint code
      run: |
        flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to production
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}
        GRAPH_CLIENT_ID: ${{ secrets.GRAPH_CLIENT_ID }}
        GRAPH_CLIENT_SECRET: ${{ secrets.GRAPH_CLIENT_SECRET }}
        GRAPH_TENANT_ID: esimplus.onmicrosoft.com
        ADMIN_IDENTITY: admin@esimplus.onmicrosoft.com
      run: |
        echo "Deploying eSIM provisioning system"
        python backend/server.py &
        
    - name: Health check
      run: |
        sleep 10
        curl -f http://localhost:8001/api/health || exit 1